# Generated by Django 4.2 on 2023-04-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_allinstanceprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allinstanceprice1",
            fields=[
                (
                    "instance_name",
                    models.CharField(
                        blank=True,
                        db_column="Instance_name",
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "linux_price",
                    models.FloatField(blank=True, db_column="Linux_Price", null=True),
                ),
                (
                    "windows_price",
                    models.FloatField(blank=True, db_column="Windows_Price", null=True),
                ),
                ("vcpu", models.IntegerField(blank=True, db_column="vCPU", null=True)),
                ("memory", models.FloatField(blank=True, null=True)),
                (
                    "storage",
                    models.CharField(
                        blank=True, db_column="Storage", max_length=20, null=True
                    ),
                ),
                (
                    "instance_family",
                    models.CharField(
                        blank=True,
                        db_column="Instance_Family",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, db_column="Region", max_length=40, null=True
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, db_column="Provider", max_length=20, null=True
                    ),
                ),
            ],
            options={"db_table": "allinstanceprice1", "managed": False,},
        ),
    ]
